### ISSUE TITLE
Adding Player Names

### ISSUE THREAD

**Issue by bsteenput** [sherpal/MBFFZ#1]
Hello! 
Your game is awesome and so beautiful!!!! 
It would be nice to have the name of the player together with the current time on the right of the game panel !

Thanks in advance :) 
Bobo

**Comment by sherpal** [comment]
Hello Bobo 😄 
Thanks for your interest in the game.

Your idea is implemented at [this commit](https://github.com/sherpal/MBFFZ/commit/1d2e7613fb6e70ef0bc469358b7f9e455a45c312).

In particular, you can have a look [here](https://github.com/sherpal/MBFFZ/blob/master/frontend/src/main/scala/gamedom/GameInfo.scala). Perhaps the display of the time could be nicer (like minutes:seconds) instead of just the number of seconds.
